### ISSUE TITLE
Art & Level Design ToDo

### ISSUE THREAD

**Issue by AnimeniacYuuto** [AnimeniacYuuto/SpaceRacer#7]
- [ ] Explosion on death
- [ ] Power up Sprites (Refer to Feature To Do)
- [ ] Create More levels
